import type { Game, PlayerProp, LiveEdge, Alert, Result, ProviderStatus } from "./types";

const ESPN_NBA_LOGO = (id: string) => `https://a.espncdn.com/i/teamlogos/nba/500/${id}.png`;
const ESPN_MLB_LOGO = (id: string) => `https://a.espncdn.com/i/teamlogos/mlb/500/${id}.png`;
const ESPN_NFL_LOGO = (id: string) => `https://a.espncdn.com/i/teamlogos/nfl/500/${id}.png`;
const ESPN_PLAYER = (id: string) => `https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/${id}.png&w=200&h=145`;

export const mockGames: Game[] = [
  {
    id: "nba-001",
    sport: "NBA",
    status: "live",
    startTime: new Date().toISOString(),
    awayTeam: { id: "bos", name: "Boston Celtics", abbreviation: "BOS", logoUrl: ESPN_NBA_LOGO("bos"), color: "#007A33" },
    homeTeam: { id: "lal", name: "Los Angeles Lakers", abbreviation: "LAL", logoUrl: ESPN_NBA_LOGO("lal"), color: "#552583" },
    awayScore: 87,
    homeScore: 82,
    period: "3rd Quarter",
    clock: "4:23",
    isLive: true,
  },
  {
    id: "nba-002",
    sport: "NBA",
    status: "live",
    startTime: new Date().toISOString(),
    awayTeam: { id: "gsw", name: "Golden State Warriors", abbreviation: "GSW", logoUrl: ESPN_NBA_LOGO("gs"), color: "#FFC72C" },
    homeTeam: { id: "phi", name: "Philadelphia 76ers", abbreviation: "PHI", logoUrl: ESPN_NBA_LOGO("phi"), color: "#006BB6" },
    awayScore: 64,
    homeScore: 71,
    period: "2nd Quarter",
    clock: "1:45",
    isLive: true,
  },
  {
    id: "nba-003",
    sport: "NBA",
    status: "scheduled",
    startTime: new Date(Date.now() + 3 * 3600000).toISOString(),
    awayTeam: { id: "mia", name: "Miami Heat", abbreviation: "MIA", logoUrl: ESPN_NBA_LOGO("mia"), color: "#98002E" },
    homeTeam: { id: "mil", name: "Milwaukee Bucks", abbreviation: "MIL", logoUrl: ESPN_NBA_LOGO("mil"), color: "#00471B" },
    awayScore: 0,
    homeScore: 0,
    period: "",
    clock: "",
    isLive: false,
  },
  {
    id: "mlb-001",
    sport: "MLB",
    status: "live",
    startTime: new Date().toISOString(),
    awayTeam: { id: "nyy", name: "New York Yankees", abbreviation: "NYY", logoUrl: ESPN_MLB_LOGO("nyy"), color: "#003087" },
    homeTeam: { id: "bos", name: "Boston Red Sox", abbreviation: "BOS", logoUrl: ESPN_MLB_LOGO("bos"), color: "#BD3039" },
    awayScore: 3,
    homeScore: 5,
    period: "7th Inning",
    clock: "Top",
    isLive: true,
  },
  {
    id: "mlb-002",
    sport: "MLB",
    status: "scheduled",
    startTime: new Date(Date.now() + 2 * 3600000).toISOString(),
    awayTeam: { id: "lad", name: "Los Angeles Dodgers", abbreviation: "LAD", logoUrl: ESPN_MLB_LOGO("lad"), color: "#005A9C" },
    homeTeam: { id: "sf", name: "San Francisco Giants", abbreviation: "SF", logoUrl: ESPN_MLB_LOGO("sf"), color: "#FD5A1E" },
    awayScore: 0,
    homeScore: 0,
    period: "",
    clock: "",
    isLive: false,
  },
  {
    id: "nfl-001",
    sport: "NFL",
    status: "scheduled",
    startTime: new Date(Date.now() + 5 * 3600000).toISOString(),
    awayTeam: { id: "kc", name: "Kansas City Chiefs", abbreviation: "KC", logoUrl: ESPN_NFL_LOGO("kc"), color: "#E31837" },
    homeTeam: { id: "buf", name: "Buffalo Bills", abbreviation: "BUF", logoUrl: ESPN_NFL_LOGO("buf"), color: "#00338D" },
    awayScore: 0,
    homeScore: 0,
    period: "",
    clock: "",
    isLive: false,
  },
];

export const mockProps: Omit<PlayerProp, "id" | "createdAt">[] = [
  {
    sport: "NBA",
    playerName: "Jayson Tatum",
    playerImage: ESPN_PLAYER("4065648"),
    teamAbbr: "BOS",
    teamLogo: ESPN_NBA_LOGO("bos"),
    opponentAbbr: "LAL",
    opponentLogo: ESPN_NBA_LOGO("lal"),
    propType: "Points",
    line: 27.5,
    avg5: 31.2,
    avg10: 29.8,
    hitRate5: 0.8,
    hitRate10: 0.7,
    lineGap: 3.7,
    consistency: 0.82,
    trend: "up",
    edgeScore: 8.9,
    confidence: "High",
    recommendation: "Strong Over",
    action: "Strong Play",
    reasoning: "Tatum averaging 31.2 over last 5 with 80% hit rate vs LAL. Line gap of 3.7 points is significant. Trending up over last 3 games.",
    redFlags: [],
    riskWarning: "",
    gameId: "nba-001",
  },
  {
    sport: "NBA",
    playerName: "LeBron James",
    playerImage: ESPN_PLAYER("1966"),
    teamAbbr: "LAL",
    teamLogo: ESPN_NBA_LOGO("lal"),
    opponentAbbr: "BOS",
    opponentLogo: ESPN_NBA_LOGO("bos"),
    propType: "Assists",
    line: 7.5,
    avg5: 9.1,
    avg10: 8.4,
    hitRate5: 0.8,
    hitRate10: 0.7,
    lineGap: 1.6,
    consistency: 0.75,
    trend: "up",
    edgeScore: 8.2,
    confidence: "High",
    recommendation: "Strong Over",
    action: "Strong Play",
    reasoning: "LeBron hitting 7+ assists in 7 of last 10. Celtics defense ranks 28th vs assists allowed to SF.",
    redFlags: [],
    riskWarning: "",
    gameId: "nba-001",
  },
  {
    sport: "NBA",
    playerName: "Stephen Curry",
    playerImage: ESPN_PLAYER("3975"),
    teamAbbr: "GSW",
    teamLogo: ESPN_NBA_LOGO("gs"),
    opponentAbbr: "PHI",
    opponentLogo: ESPN_NBA_LOGO("phi"),
    propType: "3-Pointers Made",
    line: 4.5,
    avg5: 4.8,
    avg10: 4.2,
    hitRate5: 0.6,
    hitRate10: 0.55,
    lineGap: 0.3,
    consistency: 0.65,
    trend: "flat",
    edgeScore: 6.1,
    confidence: "Medium",
    recommendation: "Lean Over",
    action: "Lean",
    reasoning: "Curry averaging 4.8 threes over last 5 but consistency is moderate. PHI allows 12.3 threes per game.",
    redFlags: ["Close line gap", "Inconsistent recent output"],
    riskWarning: "Moderate variance — moderate unit size recommended",
    gameId: "nba-002",
  },
  {
    sport: "NBA",
    playerName: "Joel Embiid",
    playerImage: ESPN_PLAYER("3059318"),
    teamAbbr: "PHI",
    teamLogo: ESPN_NBA_LOGO("phi"),
    opponentAbbr: "GSW",
    opponentLogo: ESPN_NBA_LOGO("gs"),
    propType: "Points + Rebounds",
    line: 39.5,
    avg5: 36.2,
    avg10: 37.1,
    hitRate5: 0.4,
    hitRate10: 0.45,
    lineGap: -3.3,
    consistency: 0.55,
    trend: "down",
    edgeScore: 3.2,
    confidence: "Low",
    recommendation: "Lean Under",
    action: "Avoid",
    reasoning: "Embiid has missed this line in 6 of last 10. Trending down. GSW ranks 5th in limiting big man production.",
    redFlags: ["Negative line gap", "Downward trend", "Tough matchup"],
    riskWarning: "High risk — potential trap line",
    gameId: "nba-002",
  },
  {
    sport: "NBA",
    playerName: "Jimmy Butler",
    playerImage: ESPN_PLAYER("6430562"),
    teamAbbr: "MIA",
    teamLogo: ESPN_NBA_LOGO("mia"),
    opponentAbbr: "MIL",
    opponentLogo: ESPN_NBA_LOGO("mil"),
    propType: "Points",
    line: 22.5,
    avg5: 25.4,
    avg10: 23.8,
    hitRate5: 0.8,
    hitRate10: 0.65,
    lineGap: 2.9,
    consistency: 0.72,
    trend: "up",
    edgeScore: 7.8,
    confidence: "High",
    recommendation: "Lean Over",
    action: "Lean",
    reasoning: "Butler is hot — 25.4 avg over last 5, line appears soft. MIL allowing 23+ to SFs.",
    redFlags: [],
    riskWarning: "",
    gameId: "nba-003",
  },
  {
    sport: "MLB",
    playerName: "Aaron Judge",
    playerImage: ESPN_PLAYER("33192"),
    teamAbbr: "NYY",
    teamLogo: ESPN_MLB_LOGO("nyy"),
    opponentAbbr: "BOS",
    opponentLogo: ESPN_MLB_LOGO("bos"),
    propType: "Total Bases",
    line: 1.5,
    avg5: 2.3,
    avg10: 2.1,
    hitRate5: 0.8,
    hitRate10: 0.75,
    lineGap: 0.8,
    consistency: 0.78,
    trend: "up",
    edgeScore: 8.5,
    confidence: "High",
    recommendation: "Strong Over",
    action: "Strong Play",
    reasoning: "Judge averaging 2.3 total bases last 5 with 80% hit rate. BOS starter has 5.8 ERA vs righties.",
    redFlags: [],
    riskWarning: "",
    gameId: "mlb-001",
  },
  {
    sport: "NFL",
    playerName: "Patrick Mahomes",
    playerImage: ESPN_PLAYER("3139477"),
    teamAbbr: "KC",
    teamLogo: ESPN_NFL_LOGO("kc"),
    opponentAbbr: "BUF",
    opponentLogo: ESPN_NFL_LOGO("buf"),
    propType: "Passing Yards",
    line: 272.5,
    avg5: 291.4,
    avg10: 279.8,
    hitRate5: 0.6,
    hitRate10: 0.6,
    lineGap: 18.9,
    consistency: 0.68,
    trend: "flat",
    edgeScore: 7.1,
    confidence: "Medium",
    recommendation: "Lean Over",
    action: "Lean",
    reasoning: "Mahomes averaging 291 yards last 5. BUF secondary allowing 278 avg. Moderate edge but game script dependent.",
    redFlags: ["Weather forecast — potential wind"],
    riskWarning: "Check game-time weather conditions",
    gameId: "nfl-001",
  },
];

export const mockLiveEdges: Omit<LiveEdge, "id" | "updatedAt">[] = [
  {
    propId: 1,
    playerName: "Jayson Tatum",
    playerImage: ESPN_PLAYER("4065648"),
    teamAbbr: "BOS",
    propType: "Points",
    line: 27.5,
    currentStat: 19,
    minutesPlayed: 24,
    percentComplete: 0.58,
    projectedFinal: 32.8,
    neededRemaining: 8.5,
    liveEdgePercent: 19.3,
    liveRecommendation: "Strong Live Over",
    sport: "NBA",
    gameStatus: "live",
    period: "3rd Quarter",
    clock: "4:23",
  },
  {
    propId: 2,
    playerName: "LeBron James",
    playerImage: ESPN_PLAYER("1966"),
    teamAbbr: "LAL",
    propType: "Assists",
    line: 7.5,
    currentStat: 5,
    minutesPlayed: 24,
    percentComplete: 0.58,
    projectedFinal: 8.6,
    neededRemaining: 2.5,
    liveEdgePercent: 14.7,
    liveRecommendation: "Lean Live Over",
    sport: "NBA",
    gameStatus: "live",
    period: "3rd Quarter",
    clock: "4:23",
  },
  {
    propId: 3,
    playerName: "Aaron Judge",
    playerImage: ESPN_PLAYER("33192"),
    teamAbbr: "NYY",
    propType: "Total Bases",
    line: 1.5,
    currentStat: 0,
    minutesPlayed: 0,
    percentComplete: 0.43,
    projectedFinal: 0,
    neededRemaining: 1.5,
    liveEdgePercent: -100,
    liveRecommendation: "Lean Live Under",
    sport: "MLB",
    gameStatus: "live",
    period: "7th Inning",
    clock: "Top",
  },
];

export const mockAlerts: Omit<Alert, "id" | "createdAt">[] = [
  {
    type: "strong_pregame",
    title: "Strong Edge Alert",
    message: "Jayson Tatum Points OVER 27.5 — Edge Score 8.9. Strong Play detected.",
    sport: "NBA",
    playerName: "Jayson Tatum",
    edgeScore: 8.9,
    isRead: false,
    severity: "high",
  },
  {
    type: "strong_pregame",
    title: "Strong Edge Alert",
    message: "Aaron Judge Total Bases OVER 1.5 — Edge Score 8.5. Strong Play detected.",
    sport: "MLB",
    playerName: "Aaron Judge",
    edgeScore: 8.5,
    isRead: false,
    severity: "high",
  },
  {
    type: "live_surge",
    title: "Live Surge Detected",
    message: "Jayson Tatum projected 32.8 vs line 27.5 — 19.3% above line. Strong Live Over.",
    sport: "NBA",
    playerName: "Jayson Tatum",
    edgeScore: 8.9,
    isRead: false,
    severity: "high",
  },
  {
    type: "lean",
    title: "New Lean Detected",
    message: "LeBron James Assists OVER 7.5 — Edge Score 8.2. Lean Over moving to Strong Play.",
    sport: "NBA",
    playerName: "LeBron James",
    edgeScore: 8.2,
    isRead: true,
    severity: "medium",
  },
];

export const mockResults: Omit<Result, "id" | "createdAt">[] = [
  {
    date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    sport: "NBA",
    playerName: "Jayson Tatum",
    teamAbbr: "BOS",
    opponentAbbr: "MIA",
    propType: "Points",
    line: 26.5,
    recommendation: "Strong Over",
    edgeScore: 8.7,
    status: "Win",
    profitLoss: 0.91,
    closingLine: 27.0,
  },
  {
    date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    sport: "NBA",
    playerName: "Stephen Curry",
    teamAbbr: "GSW",
    opponentAbbr: "LAC",
    propType: "3-Pointers Made",
    line: 4.5,
    recommendation: "Lean Over",
    edgeScore: 6.3,
    status: "Loss",
    profitLoss: -1.0,
    closingLine: 4.5,
  },
  {
    date: new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0],
    sport: "MLB",
    playerName: "Aaron Judge",
    teamAbbr: "NYY",
    opponentAbbr: "TB",
    propType: "Total Bases",
    line: 1.5,
    recommendation: "Strong Over",
    edgeScore: 8.1,
    status: "Win",
    profitLoss: 0.91,
    closingLine: 1.5,
  },
  {
    date: new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0],
    sport: "NFL",
    playerName: "Patrick Mahomes",
    teamAbbr: "KC",
    opponentAbbr: "LV",
    propType: "Passing Yards",
    line: 265.5,
    recommendation: "Lean Over",
    edgeScore: 7.2,
    status: "Win",
    profitLoss: 0.91,
    closingLine: 268.5,
  },
  {
    date: new Date(Date.now() - 3 * 86400000).toISOString().split("T")[0],
    sport: "NBA",
    playerName: "LeBron James",
    teamAbbr: "LAL",
    opponentAbbr: "DEN",
    propType: "Points + Rebounds",
    line: 38.5,
    recommendation: "Lean Over",
    edgeScore: 7.5,
    status: "Push",
    profitLoss: 0,
    closingLine: 38.5,
  },
];

export const mockProviders: ProviderStatus[] = [
  { name: "ESPN Scoreboard", status: "live", lastChecked: new Date().toISOString(), description: "Public ESPN scoreboard API — no key required", mockMode: false },
  { name: "The Odds API", status: "mock", lastChecked: new Date().toISOString(), description: "Set ODDS_API_KEY in environment to enable live odds", mockMode: true },
  { name: "SportsData.io", status: "mock", lastChecked: new Date().toISOString(), description: "Set SPORTSDATA_API_KEY in environment to enable", mockMode: true },
  { name: "PrizePicks Props", status: "mock", lastChecked: new Date().toISOString(), description: "Legal API key required — currently using mock props", mockMode: true },
  { name: "Underdog Fantasy", status: "mock", lastChecked: new Date().toISOString(), description: "Legal API key required — currently using mock props", mockMode: true },
  { name: "Injury Reports", status: "mock", lastChecked: new Date().toISOString(), description: "Set RAPIDAPI_KEY in environment to enable injury feeds", mockMode: true },
  { name: "Weather Data", status: "mock", lastChecked: new Date().toISOString(), description: "Weather data for outdoor games — mock mode active", mockMode: true },
];
